package boardgame.chess

import boardgame.chess.core._
import boardgame.core.XY
import org.scalatest.{ShouldMatchers, FunSpec}

class EnPassantTest extends FunSpec with ShouldMatchers{
  describe("En Passant") {
    it("should find only en passant take movement for black pawn") {
      val game = ChessGame.fromString(
        """........
          |........
          |........
          |........
          |........
          |..♟♙....
          |..♟↑....
          |........""".stripMargin)

      game.board.pieces.head.movements(game.board).size shouldBe 1
      game.board.pieces.head.movements(game.board).head shouldBe a [EnPassantTakeMovement]
    }
    it("should find 2 moves including en passant for white pawn") {
      val game = ChessGame.fromString(
        """........
          |........
          |...↓....
          |...♟♙...
          |........
          |........
          |........
          |........""".stripMargin, turn = WhiteChessPlayer)

      game.board.movements.size shouldBe 2
    }
    it("should not find en passant take move for black pawn, since king would be threatened") {
      val game = ChessGame.fromString(
        """....♖...
          |........
          |...↓....
          |...♙♟...
          |........
          |........
          |....♚...
          |........""".stripMargin)

      val board = game.board
      game.blackPlayer.pieces(board).head.movements(board).size shouldBe 1
    }
  }
}
