package boardgame.chess

import boardgame.chess.core._
import boardgame.core.XY
import org.scalatest.{ShouldMatchers, FunSpec}

class EnPassantTest extends FunSpec with ShouldMatchers{
  describe("En Passant") {
    it("should find only en passant take movement for black pawn") {
      implicit val rules = ChessRules.default
      val game = ChessGame.fromString(
        """........
          |........
          |........
          |........
          |........
          |..♟♙....
          |..♟↑....
          |........""".stripMargin, rules)

      val board = game.board
      val movements = game.blackPlayer.pieces(board).head.movements(board)

      movements.size shouldBe 1
      movements.toList.head shouldBe a [EnPassantTakeMovement]
    }
    it("should find 2 moves including en passant for white pawn") {
      implicit val rules = ChessRules.default
      val game = ChessGame.fromString(
        """........
          |........
          |...↓....
          |...♟♙...
          |........
          |........
          |........
          |........""".stripMargin, rules)

      val board = game.board
      game.whitePlayer.pieces(board).head.movements(board).size shouldBe 2
    }
    it("should not find en passant take move for black pawn, since king would be threatened") {
      implicit val rules = ChessRules.default
      val game = ChessGame.fromString(
        """....♖...
          |........
          |...↓....
          |...♙♟...
          |........
          |........
          |....♚...
          |........""".stripMargin, rules)

      val board = game.board
      game.blackPlayer.pieces(board).head.movements(board).size shouldBe 1
    }
  }
}
