package boardgame.chess

import boardgame.chess.core._
import boardgame.core.XY
import org.scalatest.{ShouldMatchers, FunSpec}

class GameEndingTest extends FunSpec with ShouldMatchers {
  describe("Game ending") {
    it("should find game over but not draw") {
      val game = ChessGame.fromString(
        """........
          |........
          |........
          |........
          |........
          |........
          |.....♛♛.
          |.......♔""".stripMargin)
      implicit val rules = game.rules
      game.isGameOver shouldBe true
      game.isDraw shouldBe false
    }

    it("should find draw and game over") {
      val game = ChessGame.fromString(
        """........
          |........
          |........
          |........
          |........
          |......♛.
          |........
          |.......♔""".stripMargin)
      implicit val rules = game.rules
      game.isDraw shouldBe true
      game.isGameOver shouldBe true
    }

    it("should not find draw nor game over") {
      val game = ChessGame.fromString(
        """........
          |........
          |........
          |........
          |......♛.
          |........
          |........
          |.......♔""".stripMargin)
      implicit val rules = game.rules
      game.isDraw shouldBe false
      game.isGameOver shouldBe false
    }

    it("should not find game over even if threatened") {
      val game = ChessGame.fromString(
        """........
          |........
          |........
          |........
          |........
          |........
          |......♛.
          |.......♔""".stripMargin)
      implicit val rules = game.rules
      game.isGameOver shouldBe false
    }

    it("white should have two CheckMateMovements available") {
      val game = ChessGame.fromString(
        """........
          |........
          |........
          |........
          |.....♛..
          |......♛.
          |........
          |.......♔""".stripMargin)
      implicit val rules = game.rules
      val board = game.board

      board.get(XY(5, 4)).get.get.owner.movements(board).filter {
        case m: ChessMovement => m.isCheckmate
        case _ => false
      }.size shouldBe 7
    }

    it("lower queen moving to the right should be a check but not a checkmate") {
      val game = ChessGame.fromString(
        """........
          |........
          |........
          |........
          |.....♛..
          |......♛.
          |........
          |.......♔""".stripMargin)
      implicit val rules = game.rules

      game.board.movement(XY(6, 5), XY(1, 0)) shouldBe
        Set(MoveMovement(new ♛(XY(6, 5), WhiteChessPlayer), XY(1, 0), isCheck = true, isCheckmate = false))
    }

    it("upper queen moving to the right should be a check and a checkmate") {
      val game = ChessGame.fromString(
        """........
          |........
          |........
          |........
          |.....♛..
          |......♛.
          |........
          |.......♔""".stripMargin)
      implicit val rules = game.rules

      game.board.movement(XY(5, 4), XY(2, 0)) shouldBe
        Set(MoveMovement(new ♛(XY(5, 4), WhiteChessPlayer), XY(2, 0), isCheck = true, isCheckmate = true))
    }

    it("upper queen moving to the left should not be a check nor a checkmate") {
      val game = ChessGame.fromString(
        """........
          |........
          |........
          |........
          |.....♛..
          |......♛.
          |........
          |.......♔""".stripMargin)
      implicit val rules = game.rules

      game.board.movement(XY(5, 4), XY(-5, 0)) shouldBe
        Set(MoveMovement(new ♛(XY(5, 4), WhiteChessPlayer), XY(-5, 0), isCheck = false, isCheckmate = false))
    }
  }
}
