package boardgame.chess

import boardgame.chess.core._
import org.scalatest.{ShouldMatchers, FunSpec}

class KingsInitialPositionTest extends FunSpec with ShouldMatchers {
  describe("King's initial position") {
    it("should determine that white king is in initial position, if white is on bottom") {
      implicit val rules = ChessRules.default
      val game = ChessGame.fromString(
        """........
          |........
          |........
          |........
          |........
          |........
          |........
          |....♔...""".stripMargin, rules)

      game.whitePlayer.kingPiece(game.board) match {
        case Some(k: ♚) => k.isInInitialPosition shouldBe true
        case _ => fail
      }
    }
    it("should determine that white king is NOT in initial position") {
      implicit val rules = ChessRules.default
      val game = ChessGame.fromString(
        """........
          |........
          |........
          |........
          |........
          |........
          |....♔...
          |........""".stripMargin, rules)

      game.whitePlayer.kingPiece(game.board) match {
        case Some(k: ♚) => k.isInInitialPosition shouldBe false
        case _ => fail
      }
    }
    it("should determine that white king is NOT in initial position if it's in black's initial position, if white is on bottom") {
      implicit val rules = ChessRules.default
      val game = ChessGame.fromString(
        """....♔...
          |........
          |........
          |........
          |........
          |........
          |........
          |........""".stripMargin, rules)

      game.whitePlayer.kingPiece(game.board) match {
        case Some(k: ♚) => k.isInInitialPosition shouldBe false
        case _ => fail
      }
    }
    it("should determine that black king is in initial position, if black is on top") {
      implicit val rules = ChessRules.default
      val game = ChessGame.fromString(
        """....♚...
          |........
          |........
          |........
          |........
          |........
          |........
          |........""".stripMargin, rules)

      game.blackPlayer.kingPiece(game.board) match {
        case Some(k: ♚) => k.isInInitialPosition shouldBe true
        case _ => fail
      }
    }
    it("should determine that black king is NOT in initial position, if black is on top") {
      implicit val rules = ChessRules.default
      val game = ChessGame.fromString(
        """........
          |........
          |....♚...
          |........
          |........
          |........
          |........
          |........""".stripMargin, rules)

      game.blackPlayer.kingPiece(game.board) match {
        case Some(k: ♚) => k.isInInitialPosition shouldBe false
        case _ => fail
      }
    }
    it("should determine that black king is NOT in initial position if it's in white's initial position, if black is on top") {
      implicit val rules = ChessRules.default
      val game = ChessGame.fromString(
        """........
          |........
          |........
          |........
          |........
          |........
          |........
          |....♚...""".stripMargin, rules)

      game.blackPlayer.kingPiece(game.board) match {
        case Some(k: ♚) => k.isInInitialPosition shouldBe false
        case _ => fail
      }
    }
  }
}
