package ostinato.chess

import ostinato.chess.core._
import ostinato.core.XY
import org.scalatest.{ShouldMatchers, FunSpec}

class EnPassantTest extends FunSpec with ShouldMatchers{
  describe("En Passant") {
    it("should find only en passant capture action for black pawn") {
      val game = ChessGame.fromString(
        """........
          |........
          |........
          |........
          |........
          |..♟♙....
          |..♟↑....
          |........""".stripMargin, turn = BlackChessPlayer)

      game.board.pieces.head.actions(game.board).size shouldBe 1
      game.board.pieces.head.actions(game.board).head shouldBe a [EnPassantCaptureAction]
    }
    it("should find 2 actions including en passant for white pawn (plus Resigning and offering Draw)") {
      val game = ChessGame.fromString(
        """........
          |........
          |...↓....
          |...♟♙...
          |........
          |........
          |........
          |........""".stripMargin, turn = WhiteChessPlayer)

      game.board.actions.size shouldBe 4
    }
    it("should not find en passant capture action for black pawn, since king would be threatened") {
      val game = ChessGame.fromString(
        """....♖...
          |........
          |...↓....
          |...♙♟...
          |........
          |........
          |....♚...
          |........""".stripMargin, turn = BlackChessPlayer)

      val board = game.board
      game.blackPlayer.pieces(board).head.actions(board).size shouldBe 1
    }
  }
}
